/*
 * The enabled assessment sample (CMP Kenya, task cmp-catalogue-20260930).
 *
 * The field set is GENERATED by tools/generate-sample.mjs from the reviewed
 * private configuration (catalogue/sample-config.json) over the private source
 * catalogue (input/catalogue-source.json, 197 entries). Only the enabled ten
 * items ever reach the browser bundle: src/lib/generated/enabled-sample.json
 * contains nothing else, and tools/check-privacy.mjs proves unselected IDs and
 * prompts are absent from dist. Do not import the source catalogue here.
 *
 * Prompts, IDs and source references are verbatim from the supplied workbook
 * extraction; this sample is an ENGINEERING PROPOSAL responding to the client
 * correction ("key questions, not random ones") and awaits content validation.
 * Typing an answer, its draft status and any future regulatory conclusion are
 * separate things; adequacy here only gates the self-reported
 * "Ready for review" action.
 */

import type { SampleReadinessStatus } from "./sample-progress";
import raw from "./generated/enabled-sample.json" with { type: "json" };

export type SampleControl =
  | "text"
  | "date"
  | "select"
  | "currency"
  | "currency_date"
  | "narrative"
  | "yes-no"
  | "conditional-text";

export interface EnabledFieldSpec {
  /** Stable supplied ID, e.g. "CP-07". */
  id: string;
  /** Verbatim prompt/label from the source workbook. Do not reword. */
  prompt: string;
  /** Short navigation label; never a replacement for the prompt. */
  shortLabel: string;
  /** Exact source clause reference (verbatim from the source description). */
  sourceRef: string;
  control: SampleControl;
  /** Only the conditional-text control offers an applicability (N/A) path. */
  allowsNa: boolean;
  selectOptions?: string[];
  sectionKey: string;
  sectionTitle: string;
  displayOrder: number;
}

export interface EnabledSection {
  key: string;
  title: string;
  phaseOrder: number;
  items: EnabledFieldSpec[];
}

interface RawRuntime {
  sampleVersion: string;
  sourceRevision: string;
  sourceSha256: string;
  sourceFileSha256: string;
  sections: Array<{
    key: string;
    title: string;
    phaseOrder: number;
    items: Array<{
      id: string;
      prompt: string;
      shortLabel: string;
      sourceRef: string;
      control: SampleControl;
      allowsNa: boolean;
      displayOrder: number;
      selectOptions?: string[];
    }>;
  }>;
}

const runtime = raw as RawRuntime;

/** Fail fast on an inconsistent generated file — a build/config error, never a silent wrong form. */
function buildSample(): {
  sampleVersion: string;
  sourceRevision: string;
  fields: EnabledFieldSpec[];
  sections: EnabledSection[];
} {
  if (!Array.isArray(runtime.sections) || runtime.sections.length === 0) {
    throw new Error("enabled-sample.json is empty — run npm run sample:generate");
  }
  const fields: EnabledFieldSpec[] = [];
  const sections: EnabledSection[] = runtime.sections.map((section) => ({
    key: section.key,
    title: section.title,
    phaseOrder: section.phaseOrder,
    items: section.items.map((item) => ({
      ...item,
      sectionKey: section.key,
      sectionTitle: section.title,
    })),
  }));
  for (const section of sections) {
    for (const item of section.items) {
      if (fields.some((existing) => existing.id === item.id)) {
        throw new Error(`enabled-sample.json has duplicate ID ${item.id}`);
      }
      fields.push(item);
    }
  }
  if (fields.length === 0) throw new Error("enabled-sample.json has no items");
  return {
    sampleVersion: runtime.sampleVersion,
    sourceRevision: runtime.sourceRevision,
    fields,
    sections,
  };
}

const sample = buildSample();

export const enabledFields: readonly EnabledFieldSpec[] = sample.fields;
export const enabledSections: readonly EnabledSection[] = sample.sections;
export const EXPECTED_SAMPLE_VERSION = sample.sampleVersion;
export const SAMPLE_SOURCE_REVISION = sample.sourceRevision;

export const fieldById: ReadonlyMap<string, EnabledFieldSpec> = new Map(
  enabledFields.map((field) => [field.id, field] as const),
);

/** Transient answer for one field (React state / saved draft shape). */
export interface SampleAnswer {
  /** Recorded state, separate from the typed answer. */
  status: SampleReadinessStatus;
  /** text control, narrative and conditional-details text. */
  text: string;
  /** date control and the as-at date of currency_date. */
  dateValue: string;
  /** currency / currency_date amount, exactly as typed. */
  numberValue: string;
  /** select control value ("" until chosen). */
  selectValue: string;
  /** yes-no control (legacy special; "" until chosen). */
  yesNo: "" | "yes" | "no";
  /** Recorded N/A reason (conditional-text items only). */
  naReason: string;
}

export function initialSampleAnswer(): SampleAnswer {
  return { status: "not_started", text: "", dateValue: "", numberValue: "", selectValue: "", yesNo: "", naReason: "" };
}

/*
 * Number guards for currency controls: finite and non-negative. The database
 * re-checks this at the boundary (numeric column constraint + trigger).
 */
export function numberValueIssue(numberValue: string): string | null {
  if (numberValue.trim() === "") return null;
  const value = Number(numberValue.trim());
  if (!Number.isFinite(value)) {
    return "Enter a plain number (digits with an optional decimal point); words, commas and very large exponents are not accepted.";
  }
  if (value < 0) {
    return "Enter a non-negative amount.";
  }
  return null;
}

export function parseNumberValue(numberValue: string): number | null {
  const trimmed = numberValue.trim();
  if (trimmed === "") return null;
  const value = Number(trimmed);
  return Number.isFinite(value) && value >= 0 ? value : null;
}

/** ISO date guard (shared with the database's isfinite/range check). */
export function dateValueIssue(dateValue: string): string | null {
  if (dateValue === "") return null;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(dateValue)) {
    return "Enter a real calendar date (YYYY-MM-DD); special values such as “infinity” are not accepted.";
  }
  const parts = dateValue.split("-").map((part) => Number(part));
  const candidate = new Date(Date.UTC(parts[0], parts[1] - 1, parts[2]));
  if (
    candidate.getUTCFullYear() !== parts[0] ||
    candidate.getUTCMonth() !== parts[1] - 1 ||
    candidate.getUTCDate() !== parts[2]
  ) {
    return "That date does not exist on the calendar (for example 31 April or 29 February on a non-leap year).";
  }
  if (dateValue < "1600-01-01" || dateValue > "3000-01-01") {
    return "Enter a date between 1600-01-01 and 3000-01-01.";
  }
  return null;
}

function dateOk(value: string): boolean {
  return value !== "" && dateValueIssue(value) === null;
}

function numberOk(value: string): boolean {
  return value.trim() !== "" && numberValueIssue(value) === null;
}

/*
 * Whether the typed answer is adequate for the self-reported "Ready for
 * review" action. A recorded No to a yes-no item is a complete answer on its
 * own; Yes requires the details text. Adequacy is a completeness gate only —
 * never a regulatory judgement.
 */
export function answerAdequate(field: Pick<EnabledFieldSpec, "control">, answer: SampleAnswer): boolean {
  switch (field.control) {
    case "text":
      return answer.text.trim() !== "";
    case "date":
      return dateOk(answer.dateValue);
    case "select":
      return answer.selectValue !== "";
    case "currency":
      return numberOk(answer.numberValue);
    case "currency_date":
      return numberOk(answer.numberValue) && dateOk(answer.dateValue);
    case "narrative":
      return answer.text.trim() !== "";
    case "yes-no":
      return answer.yesNo === "no" || (answer.yesNo === "yes" && answer.text.trim() !== "");
    case "conditional-text":
      return answer.text.trim() !== "";
  }
}

/*
 * What is still missing for adequacy, shown next to a disabled
 * "Ready for review" action (recognition, not recall).
 */
export function missingForReview(
  field: Pick<EnabledFieldSpec, "control">,
  answer: SampleAnswer,
): string | null {
  if (answerAdequate(field, answer)) return null;
  switch (field.control) {
    case "text":
      return "Enter the name before marking it ready for review.";
    case "date":
      return "Enter a valid date before marking it ready for review.";
    case "select":
      return "Choose a listing segment before marking it ready for review.";
    case "currency":
      return "Enter a non-negative amount before marking it ready for review.";
    case "currency_date":
      return numberOk(answer.numberValue)
        ? "Enter the as-at date before marking it ready for review."
        : dateOk(answer.dateValue)
          ? "Enter a non-negative amount before marking it ready for review."
          : "Enter the amount and its as-at date before marking it ready for review.";
    case "narrative":
      return "Write the narrative before marking it ready for review.";
    case "yes-no":
      return answer.yesNo === "yes"
        ? "Describe the circumstances before marking it ready for review."
        : "Record the Yes/No answer before marking it ready for review.";
    case "conditional-text":
      return "Describe the arrangement, or record that it does not apply, before marking it ready for review.";
  }
}

/*
 * The worked example presenter affordance: purely synthetic in-memory values
 * for the anonymous preview — no real company. Fixed arithmetic:
 * 7 of the 10 selected items ready for review, no N/A items configured,
 * Q-BUS-03 (draft narrative), Q-RISK-01 (empty) and Q-FIN-02 (empty) are the
 * three gaps → 7 / 10 = 70.00%.
 */
export function workedExampleAnswers(): Record<string, SampleAnswer> {
  const answers: Record<string, SampleAnswer> = {};
  for (const field of enabledFields) answers[field.id] = initialSampleAnswer();
  const ready = (id: string, patch: Partial<SampleAnswer>) => {
    answers[id] = { ...initialSampleAnswer(), status: "ready", ...patch };
  };
  const draft = (id: string, patch: Partial<SampleAnswer>) => {
    answers[id] = { ...initialSampleAnswer(), status: "in_progress", ...patch };
  };
  ready("CP-01", { text: "Demo Placeholder Industries Ltd" });
  ready("CP-07", { dateValue: "1970-01-01" }); // unmistakably a demo epoch date
  ready("CP-13", { selectValue: "MIMS" });
  ready("SC-03", { numberValue: "5000000" });
  ready("CP-16", { numberValue: "120000000", dateValue: "2025-12-31" });
  ready("Q-BUS-01", {
    text: "Demo placeholder: the fictional company manufactures demonstration components; component sales contribute most of the revenue in this synthetic example.",
  });
  draft("Q-BUS-03", {
    text: "Demo placeholder: a partial draft describing fictional domestic and export markets.",
  });
  ready("Q-FIN-03", {
    text: "Demo placeholder: in this fictional example the board is satisfied that capital is adequate for the next nine months.",
  });
  // Q-RISK-01 and Q-FIN-02 stay untouched (not started) — the remaining gaps.
  return answers;
}
